spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root1234
    url: jdbc:mysql://localhost:3306/project
    initialization-mode: always
    continue-on-error: true
  application:
    name: eshop-service    
  mail:
    default-encoding: UTF-8
    host: smtp.gmail.com
    username: anshayush2704@gmail.com
    password: ijadsdvtsfhhylue 		
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    protocol: smtp
    test-connection: false

  jpa:
    show-sql: false
#    generate-ddl: false
    hibernate:
      id:
        new_generator_mappings: false;
      ddl-auto: none
    database: mysql
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false;
    database-platform: org.hibernate.dialect.MySQL5Dialect
  #      dialect: org.hibernate.dialect.MySQL5Dialect

#  jackson:
#    default-property-inclusion: non_null
#  redis:
#    host: localhost
#    port: 6379
#  freemarker:
#      cache: false




  queries:
    users-query: select email, password, active from users where email=?
    roles-query: select email, role from users where email=?
server:
  servlet:
    contextPath: /api
  port: 8084
jwtSecret: me.zhulin
jwtExpiration: 86400